### ISSUE TITLE
Move this repo to frictionlessdata organisation?

### ISSUE THREAD

**Issue by roll** [okfn/data.okfn.org#213] opened 2016-03-23 13:39 UTC
Related - https://github.com/okfn/data.okfn.org/issues/206

If follow `opentrials` and `openspending` patterns it will be org-level issue tracker.

**Comment by danfowler** [comment] 2016-03-23 13:40
@roll yes, I would like to this.

**Comment by rgrp** [comment] 2016-03-23 14:03
DUPLICATE of #206

**Closed by rgrp** 2016-03-23 14:03 UTC
