### ISSUE TITLE
DataPackage.json Creator error - licenses not working

### ISSUE THREAD

**Issue by mchelen** [okfn/data.okfn.org#135] opened 2014-12-09 08:10 UTC
The tool at http://data.okfn.org/tools/create is not letting me select a license, the dropdown is blank and greyed out.

**Comment by sxren** [comment] 2015-01-25 15:20
@rgrp Oops. Just noticed the comment you added to #142 about this issue. Would you like me to attach the pull request to this issue or...? I'll search next time. Sorry about that.

**Comment by rgrp** [comment] 2015-01-25 15:45
@sxren don't worry - good to have the patch. I think your solution fixes this issue (not the other one). However note the comments there about how we probably want to improve this more medium-term (i.e. patch upstream in datapackage-init ...).

**Comment by rgrp** [comment] 2015-01-25 15:55
@sxren asked:

The Licenses select field options at tools/create should run off https://github.com/okfn/licenses.

@rgrp from the http://licenses.opendefinition.org api? or directly from github? thanks!

**Comment by rgrp** [comment] 2015-01-25 15:56
@sxren right now I think we should just pull a very short list of potential licenses from that repo and use it for that field with their IDs and if folks don't use that we give them option to add a name + url (cf the data package spec and definition of licenses field).

**Comment by sxren** [comment] 2015-02-04 02:57
@rgrp

1. the issue involves three projects: https://github.com/okfn/licenses, https://github.com/okfn/datapackage-init, and this one 
1. https://github.com/okfn/licenses/issues/31#issuecomment-39012594 proposes rewriting https://github.com/okfn/licenses as a node module—if we want more than a quick fix, this seems like the place to start; what do you think?
1. if https://github.com/okfn/licenses is a node modue, should that be a different project? or would you prefer everything (data and static github pages api) in one place?
1. https://github.com/okfn/data.okfn.org/blob/master/views/tools/dp/create.html is essentially a duplicate of the https://github.com/okfn/datapackage-init demo app, minus the broken licenses field. i'm not well versed in node + express; could that demo app be used as the tools/create page in this project? if so, what would be the cons of doing that?
1. given the above, a quick fix here makes sense because broken and volunteer time, not so much. options:
    1. remove the licenses select field
    1. fix the licenses select field
        * proposed short list: ODC-PDDL-1.0, ODC-BY-1.0, Other
        * ODC-PDDL-1.0 vs PDDL-1.0—are both correct? which is preferred?

thank you.

**Comment by rgrp** [comment] 2015-02-04 06:21
@sxren I agree on quick-fix (ultimately okfn/licenses should become simple enough to submodule or similar but let's leave that for now).

* Your basic list plus ODC-ODbL + CC-Zero, CC-By-4.0 and CC-By-SA-4.0 looks good
* We just need name, url and id for our work

This page https://github.com/okfn/data.okfn.org/blob/master/views/tools/dp/create.html does indeed directly reuse the demo app. If we fix the demo app then it will be very simple to deploy to the create page so let's start there.

**Comment by sxren** [comment] 2015-02-04 09:05
@rgrp 

* clarification: instead of sourcing app.js and bundle.js into the tools/create view from the labs website, could the tools/create route run the demo app, view and all? app within app. no deploy to labs required to update tools/create. one less page to maintain. or is that a not a thing in express?

* ODC-PDDL-1.0 vs PDDL-1.0—which is preferred? or am i being overly conscious of an unimportant detail?

thanks.

**Comment by rgrp** [comment] 2015-02-04 13:49
@sxren maybe but I'm not sure of exact way to do that plus I want the demo app in datapackage-init as an example for others not just our use.

Re identifiers for licenses we should use those in github.com/okfn/licenses

**Comment by sxren** [comment] 2015-02-04 21:18
@rgrp have a look at the [pull request](https://github.com/okfn/datapackage-init/pull/5) to datapackage-init and let me know what you think. suggestions always welcome. thank you.

**Comment by sxren** [comment] 2015-02-05 21:38
@rgrp importing https://github.com/sxren/datapackage-licenses into both datapackage-init and data.okfn.org, along with my original fix to data.okfn.org and a small variation on my changes to datapackage-init would wrap up the license issue in both projects. i don't see a place to stick the same information in datapackage-init where the data would also be accessible to nunjucks. i gave you access to https://github.com/sxren/datapackage-licenses in case you're ok with this approach and want to move it to okfn. open to suggestions as always.

**Comment by rgrp** [comment] 2015-02-06 09:23
@sxren I don't mind doing the simplest thing possible - so whatever works for you. I do note your PR on the datapackage-init looked pretty good https://github.com/okfn/datapackage-init/pull/5 - that's the way I'd e going and then reusing / copying over to data.okfn.org (I know it is a bit round about but it is definitely cleaner way to go and allows others to reuse demo code in other projects - which is important).

**Comment by rgrp** [comment] 2015-02-22 15:18
FIXED. http://data.okfn.org/tools/create (fixed last weekend).

**Closed by rgrp** 2015-02-22 15:18 UTC
Labels: bug, Priority: ★★★, Tools
