### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by akuckartz** [okfn/data.okfn.org#159] opened 2015-02-28 12:06 UTC
Would JSON-LD serializations be in scope? If yes, then I might be interested to help.

**Comment by rgrp** [comment] 2015-03-02 09:18
@akuckartz JSON-LD serializations of what (data or metadata)? Definitely welcome help!

**Comment by akuckartz** [comment] 2015-04-12 17:29
@rgrp JSON-LD for both data and metadata, but low hanging fruit first! I will attempt to prepare a proposal. You may assign this issue to me.

**Comment by rgrp** [comment] 2015-09-06 15:38
@akuckartz how are you doing here?

**Comment by danfowler** [comment] 2016-03-24 11:28
Closing in favor of active discussion here: https://github.com/dataprotocols/dataprotocols/issues/218

**Closed by danfowler** 2016-03-24 11:28 UTC

**Comment by rgrp** [comment] 2016-03-25 16:09
@danfowler these two things are completely different - this is about outputting JSON-LD serializations for *data* not metadata.

I agree on closing simply because of lack of response but this is not a DUPLICATE of https://github.com/dataprotocols/dataprotocols/issues/218

**Comment by akuckartz** [comment] 2016-03-25 19:08
Both data and metadata is data. So these issues are related.

**Comment by rgrp** [comment] 2016-03-27 08:30
@akuckartz do you have any updates here - would love to see anything you can provide.

**Comment by danfowler** [comment] 2016-03-28 08:16
@rgrp OK. If there's more we can do here, I can re-open and rename the issue so it is clearer to people reading through these issues?

**Comment by rgrp** [comment] 2016-03-29 10:03
@danfowler agreed and up to @akuckartz - if he is up for doing something and clarifying that is great. Otherwise I suggest we close for now.
