### ISSUE TITLE
DataPackage Creator allows only 1 file

### ISSUE THREAD

**Issue by michalskop** [okfn/data.okfn.org#142] opened 2015-01-22 03:29 UTC
The DataPackage Creator (http://data.okfn.org/tools/create) allows only one file in the datapackage. It would be rather useful to allow to add multiple files in the datapackage. (Where are the source js file on github?)

(Also, there are no licenses to choose from.)

**Comment by rgrp** [comment] 2015-01-23 08:02
@michael this is a great point and we really want to improve this and the creator in general.

To explain how this currently works quickly (so you can contribute if you wish):

- Source JS is this repo: https://github.com/okfn/datapackage-init (which is nodejs / browser js)
- The core of that is a simple nodejs library (index.js)
- There is a browser-only demo here https://github.com/okfn/datapackage-init/tree/master/demo which users browserify to turn nodejs lib into a browser js lib
  - Strictly, at the moment, this browser only lib runs off this https://github.com/okfn/datapackage-init/blob/master/demo/lib.js (which only use jts-infer and does not use the datapackage-index index.js stuff)
- this demo gets published to http://okfnlabs.org/datapackage-init/demo/ (by gh-pages)
- the data.okfn.org site then directly links http://okfnlabs.org/datapackage-init/demo/bundle.js etc

So, to improve start hacking directly in https://github.com/okfn/datapackage-init and specifically https://github.com/okfn/datapackage-init/tree/master/demo (which is also easier to do as very simple lib)

I note re licenses what we would really like to do is start running off https://github.com/okfn/licenses (or something similar) but to start with we could just hard-code this stuff (copy/paste json list from https://github.com/okfn/licenses)

**Comment by rgrp** [comment] 2015-01-25 13:28
Note licenses stuff is duplicate of #135

**Comment by rgrp** [comment] 2015-02-16 07:52
FIXED. See https://github.com/okfn/datapackage-init/issues/16 (this largely gets fixed in datapackage-init)

**Closed by rgrp** 2015-02-16 07:52 UTC
Labels: Priority: ★★, Tools
